#!/bin/bash
multichain-cli metar subscribe AF 
multichain-cli metar subscribe AX 
multichain-cli metar subscribe AL 
multichain-cli metar subscribe DZ 
multichain-cli metar subscribe AS 
multichain-cli metar subscribe AD 
multichain-cli metar subscribe AO 
multichain-cli metar subscribe AI 
multichain-cli metar subscribe AQ 
multichain-cli metar subscribe AG 
multichain-cli metar subscribe AR 
multichain-cli metar subscribe AM 
multichain-cli metar subscribe AW 
multichain-cli metar subscribe AU 
multichain-cli metar subscribe AT 
multichain-cli metar subscribe AZ 
multichain-cli metar subscribe BS 
multichain-cli metar subscribe BH 
multichain-cli metar subscribe BD 
multichain-cli metar subscribe BB 
multichain-cli metar subscribe BY 
multichain-cli metar subscribe BE 
multichain-cli metar subscribe BZ 
multichain-cli metar subscribe BJ 
multichain-cli metar subscribe BM 
multichain-cli metar subscribe BT 
multichain-cli metar subscribe BO 
multichain-cli metar subscribe BQ 
multichain-cli metar subscribe BA 
multichain-cli metar subscribe BW 
multichain-cli metar subscribe BV 
multichain-cli metar subscribe BR 
multichain-cli metar subscribe IO 
multichain-cli metar subscribe BN 
multichain-cli metar subscribe BG 
multichain-cli metar subscribe BF 
multichain-cli metar subscribe BI 
multichain-cli metar subscribe KH 
multichain-cli metar subscribe CM 
multichain-cli metar subscribe CA 
multichain-cli metar subscribe CV 
multichain-cli metar subscribe KY 
multichain-cli metar subscribe CF 
multichain-cli metar subscribe TD 
multichain-cli metar subscribe CL 
multichain-cli metar subscribe CN 
multichain-cli metar subscribe CX 
multichain-cli metar subscribe CC 
multichain-cli metar subscribe CO 
multichain-cli metar subscribe KM 
multichain-cli metar subscribe CG 
multichain-cli metar subscribe CD 
multichain-cli metar subscribe CK 
multichain-cli metar subscribe CR 
multichain-cli metar subscribe CI 
multichain-cli metar subscribe HR 
multichain-cli metar subscribe CU 
multichain-cli metar subscribe CW 
multichain-cli metar subscribe CY 
multichain-cli metar subscribe CZ 
multichain-cli metar subscribe DK 
multichain-cli metar subscribe DJ 
multichain-cli metar subscribe DM 
multichain-cli metar subscribe DO 
multichain-cli metar subscribe EC 
multichain-cli metar subscribe EG 
multichain-cli metar subscribe SV 
multichain-cli metar subscribe GQ 
multichain-cli metar subscribe ER 
multichain-cli metar subscribe EE 
multichain-cli metar subscribe ET 
multichain-cli metar subscribe FK 
multichain-cli metar subscribe FO 
multichain-cli metar subscribe FJ 
multichain-cli metar subscribe FI 
multichain-cli metar subscribe FR 
multichain-cli metar subscribe GF 
multichain-cli metar subscribe PF 
multichain-cli metar subscribe TF 
multichain-cli metar subscribe GA 
multichain-cli metar subscribe GM 
multichain-cli metar subscribe GE 
multichain-cli metar subscribe DE 
multichain-cli metar subscribe GH 
multichain-cli metar subscribe GI 
multichain-cli metar subscribe GR 
multichain-cli metar subscribe GL 
multichain-cli metar subscribe GD 
multichain-cli metar subscribe GP 
multichain-cli metar subscribe GU 
multichain-cli metar subscribe GT 
multichain-cli metar subscribe GG 
multichain-cli metar subscribe GN 
multichain-cli metar subscribe GW 
multichain-cli metar subscribe GY 
multichain-cli metar subscribe HT 
multichain-cli metar subscribe HM 
multichain-cli metar subscribe VA 
multichain-cli metar subscribe HN 
multichain-cli metar subscribe HK 
multichain-cli metar subscribe HU 
multichain-cli metar subscribe IS 
multichain-cli metar subscribe IN 
multichain-cli metar subscribe ID 
multichain-cli metar subscribe IR 
multichain-cli metar subscribe IQ 
multichain-cli metar subscribe IE 
multichain-cli metar subscribe IM 
multichain-cli metar subscribe IL 
multichain-cli metar subscribe IT 
multichain-cli metar subscribe JM 
multichain-cli metar subscribe JP 
multichain-cli metar subscribe JE 
multichain-cli metar subscribe JO 
multichain-cli metar subscribe KZ 
multichain-cli metar subscribe KE 
multichain-cli metar subscribe KI 
multichain-cli metar subscribe KP 
multichain-cli metar subscribe KR 
multichain-cli metar subscribe KW 
multichain-cli metar subscribe KG 
multichain-cli metar subscribe LA 
multichain-cli metar subscribe LV 
multichain-cli metar subscribe LB 
multichain-cli metar subscribe LS 
multichain-cli metar subscribe LR 
multichain-cli metar subscribe LY 
multichain-cli metar subscribe LI 
multichain-cli metar subscribe LT 
multichain-cli metar subscribe LU 
multichain-cli metar subscribe MO 
multichain-cli metar subscribe MK 
multichain-cli metar subscribe MG 
multichain-cli metar subscribe MW 
multichain-cli metar subscribe MY 
multichain-cli metar subscribe MV 
multichain-cli metar subscribe ML 
multichain-cli metar subscribe MT 
multichain-cli metar subscribe MH 
multichain-cli metar subscribe MQ 
multichain-cli metar subscribe MR 
multichain-cli metar subscribe MU 
multichain-cli metar subscribe YT 
multichain-cli metar subscribe MX 
multichain-cli metar subscribe FM 
multichain-cli metar subscribe MD 
multichain-cli metar subscribe MC 
multichain-cli metar subscribe MN 
multichain-cli metar subscribe ME 
multichain-cli metar subscribe MS 
multichain-cli metar subscribe MA 
multichain-cli metar subscribe MZ 
multichain-cli metar subscribe MM 
multichain-cli metar subscribe NA 
multichain-cli metar subscribe NR 
multichain-cli metar subscribe NP 
multichain-cli metar subscribe NL 
multichain-cli metar subscribe NC 
multichain-cli metar subscribe NZ 
multichain-cli metar subscribe NI 
multichain-cli metar subscribe NE 
multichain-cli metar subscribe NG 
multichain-cli metar subscribe NU 
multichain-cli metar subscribe NF 
multichain-cli metar subscribe MP 
multichain-cli metar subscribe NO 
multichain-cli metar subscribe OM 
multichain-cli metar subscribe PK 
multichain-cli metar subscribe PW 
multichain-cli metar subscribe PS 
multichain-cli metar subscribe PA 
multichain-cli metar subscribe PG 
multichain-cli metar subscribe PY 
multichain-cli metar subscribe PE 
multichain-cli metar subscribe PH 
multichain-cli metar subscribe PN 
multichain-cli metar subscribe PL 
multichain-cli metar subscribe PT 
multichain-cli metar subscribe PR 
multichain-cli metar subscribe QA 
multichain-cli metar subscribe RE 
multichain-cli metar subscribe RO 
multichain-cli metar subscribe RU 
multichain-cli metar subscribe RW 
multichain-cli metar subscribe BL 
multichain-cli metar subscribe SH 
multichain-cli metar subscribe KN 
multichain-cli metar subscribe LC 
multichain-cli metar subscribe MF 
multichain-cli metar subscribe PM 
multichain-cli metar subscribe VC 
multichain-cli metar subscribe WS 
multichain-cli metar subscribe SM 
multichain-cli metar subscribe ST 
multichain-cli metar subscribe SA 
multichain-cli metar subscribe SN 
multichain-cli metar subscribe RS 
multichain-cli metar subscribe SC 
multichain-cli metar subscribe SL 
multichain-cli metar subscribe SG 
multichain-cli metar subscribe SX 
multichain-cli metar subscribe SK 
multichain-cli metar subscribe SI 
multichain-cli metar subscribe SB 
multichain-cli metar subscribe SO 
multichain-cli metar subscribe ZA 
multichain-cli metar subscribe GS 
multichain-cli metar subscribe SS 
multichain-cli metar subscribe ES 
multichain-cli metar subscribe LK 
multichain-cli metar subscribe SD 
multichain-cli metar subscribe SR 
multichain-cli metar subscribe SJ 
multichain-cli metar subscribe SZ 
multichain-cli metar subscribe SE 
multichain-cli metar subscribe CH 
multichain-cli metar subscribe SY 
multichain-cli metar subscribe TW 
multichain-cli metar subscribe TJ 
multichain-cli metar subscribe TZ 
multichain-cli metar subscribe TH 
multichain-cli metar subscribe TL 
multichain-cli metar subscribe TG 
multichain-cli metar subscribe TK 
multichain-cli metar subscribe TO 
multichain-cli metar subscribe TT 
multichain-cli metar subscribe TN 
multichain-cli metar subscribe TR 
multichain-cli metar subscribe TM 
multichain-cli metar subscribe TC 
multichain-cli metar subscribe TV 
multichain-cli metar subscribe UG 
multichain-cli metar subscribe UA 
multichain-cli metar subscribe AE 
multichain-cli metar subscribe GB 
multichain-cli metar subscribe US 
multichain-cli metar subscribe UM 
multichain-cli metar subscribe UY 
multichain-cli metar subscribe UZ 
multichain-cli metar subscribe VU 
multichain-cli metar subscribe VE 
multichain-cli metar subscribe VN 
multichain-cli metar subscribe VG 
multichain-cli metar subscribe VI 
multichain-cli metar subscribe WF 
multichain-cli metar subscribe EH 
multichain-cli metar subscribe YE 
multichain-cli metar subscribe ZM 
multichain-cli metar subscribe ZW 

